### ISSUE TITLE
How can I use this library for arbitrary length data?

### ISSUE THREAD

**Issue by akiradeveloper** [dsprenkels/sss-rs#10]
The function looks only accept 64B data. To apply this scheme for arbitrary length data, do I need to call the function multiple times?

Say I want to create shares from 128B data, create the shares from the first and second 64B independently (calling `create_shares` twice) and concatenate the each share is the best way to apply this library to 128B data? From the share, I think I can reconstruct the first and second 64B by calling `combine_shares` twice.

**Comment by dsprenkels** [comment]
Hey @akiradeveloper. The regular API uses an AEAD to protect the shares against tampering. However, the `hazmat` module exposes the original key-sharing functionality. You can use that module to secret-share longer or shorter data.

See: https://docs.rs/shamirsecretsharing/latest/shamirsecretsharing/hazmat/index.html

**Comment by nathanfranke** [comment]
I recommend encrypting the data with an AES key, then putting the AES key into the secret share. AES256 - 32 bytes, so you will need to pad the length to 64 bytes. I use [ring](https://github.com/briansmith/ring) for my AES logic.

**Comment by dsprenkels** [comment]
Assuming this question has been answered.
