### ISSUE TITLE
Redistributing secret shares to new members without recovering the original secret

### ISSUE THREAD

**Issue by nathanfranke** [dsprenkels/sss-rs#11]
I am interested in utilizing the algorithm described in [this paper](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.55.2968&rep=rep1&type=pdf) (I found it through [this StackExchange answer](https://crypto.stackexchange.com/a/42920)).

Is this algorithm within the scope of this library? I am looking forward to your input.

**Comment by dsprenkels** [comment]
Hiya! Compared to Shamir secret sharing this is a pretty complicated and unfortunately not in the scope of this project.
